imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

    - { resource: "settings/general_params.yml" }
    - { resource: "settings/email_params.yml" }
    - { resource: "settings/url_params.yml" }
    - { resource: "settings/template_params.yml" }
    - { resource: "settings/user_params.yml" }
    - { resource: "settings/template_params.yml" }
    - { resource: "settings/core_params.yml" }
    - { resource: "settings/developer_params.yml" }

    - { resource: "@AccountBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled: true
        enable_annotations: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    templating:
        engines: ['php', 'twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FosUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AccountBundle\Entity\User
#    use_username_form_type: true
#    use_listener:           true
#    use_flash_notifications: true
    from_email:
        address:        webmaster@example.com
        sender_name:    Admin
#    profile:
#        form:
#            type:               fos_user_profile
#            handler:            fos_user.profile.form.handler.default
#            name:               fos_user_profile_form
#            validation_groups:  [Profile, Default]
#    change_password:
#        form:
#            type:               fos_user_change_password
#            handler:            fos_user.change_password.form.handler.default
#            name:               fos_user_change_password_form
#            validation_groups:  [ChangePassword, Default]
#    registration:
#        confirmation:
#            from_email:
#                    address: you@example.com
#                    sender_name: You
#            enabled:    false # change to true for required email confirmation
#            template:   FOSUserBundle:Registration:email.txt.twig
#        form:
#            type:               fos_user_registration
#            handler:            fos_user.registration.form.handler.default
#            name:               fos_user_registration_form
#            validation_groups:  [Registration, Default]
#    resetting:
#        token_ttl: 86400
#        email:
#            from_email: # Use this node only if you don't want the global email address for the resetting email
#                address:        ...
#                sender_name:    ...
#            template:   FOSUserBundle:Resetting:email.txt.twig
#        form:
#            type:               fos_user_resetting
#            handler:            fos_user.resetting.form.handler.default
#            name:               fos_user_resetting_form
#            validation_groups:  [ResetPassword, Default]
#    service:
#        mailer:                 fos_user.mailer.default
#        email_canonicalizer:    fos_user.util.canonicalizer.default
#        username_canonicalizer: fos_user.util.canonicalizer.default
#        token_generator:        fos_user.util.token_generator.default
#        user_manager:           fos_user.user_manager.default
#    template:
#        engine: twig
#    group:
#        group_class:    ~ # Required when using groups
#        group_manager:  fos_user.group_manager.default
#        form:
#            type:               fos_user_group
#            handler:            fos_user.group.form.handler.default
#            name:               fos_user_group_form
#            validation_groups:  [Registration, Default]

# FOSRestBundle Configuration
#fos_rest:
#    body_listener: false
#    param_fetcher_listener: force
#    view:
#        view_response_listener: 'force'
#        formats:
#            json: true
#            xml: false
#            rss: false
#        mime_types:
#            json:   ['application/json', 'application/x-json']
#            jpg:    ['image/jpeg']
#            png:    ['image/png']
#    routing_loader:
#        default_format:  json
#        include_format:  false
#    format_listener:
#        enabled: true
#        rules:
#            - { path: ^/api, priorities: ['json'], fallback_format: json, prefer_extension: true }
#            - { path: ^/, priorities: [ ], fallback_format: html, prefer_extension: true }
#    exception:
#        enabled: true

# LexikJWTBundle Configuration
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

# NelmioCorsBundle Configuration
nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600